/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafx;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.stage.Stage;

public class App extends Application {


    @Override
    public void start(Stage primaryStage) throws Exception {

        Group group = new Group();

        Scene scene = new Scene(group, 500, 500);

        primaryStage.setScene(scene);
        primaryStage.show();
        
    }

    private void wyswietlAlert(){
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Tytuł okna");
        alert.setHeaderText("Przykładowy nagłówek");
        alert.setContentText("Przykładowy tekst");

        alert.showAndWait();
    }
}
