/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafx;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

class MyButton extends Button{

    MyButton(int no){
        super(""+no);

        setMaxWidth(Double.MAX_VALUE);
        HBox.setHgrow(this, Priority.ALWAYS);

        setOnMouseClicked(event -> {
            wyswietlAlert(no);
        });
    }

    private void wyswietlAlert(int no){
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Tytuł okna");
        alert.setHeaderText("Przykładowy nagłówek");
        alert.setContentText(""+no);

        alert.showAndWait();
    }
}

public class App extends Application {


    @Override
    public void start(Stage primaryStage) throws Exception {

        Group group = new Group();

        Scene scene = new Scene(group, 500, 500);

        primaryStage.setScene(scene);
        primaryStage.show();

        MyButton button0 = new MyButton(0);
        MyButton button1 = new MyButton(1);
        MyButton button2 = new MyButton(2);
        MyButton button3 = new MyButton(100);

        HBox hbox = new HBox(button0,button1,button2,button3);
        hbox.setPrefWidth(500);



        BackgroundFill bf = new BackgroundFill(Color.AZURE,null,null);

        hbox.setBackground(new Background(bf));


        group.getChildren().add(hbox);

    }
}
