/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafx;

import javafx.application.Application;
import javafx.collections.ObservableList;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

class MyButton extends Button {
    private int mNumber;
    private int mOriginalNumber;

    MyButton(int no) {
        super("" + no);

        mOriginalNumber = no;
        mNumber = no;

        setMaxWidth(Double.MAX_VALUE);
        setMaxHeight(Double.MAX_VALUE);


        GridPane.setVgrow(this, Priority.ALWAYS);
        GridPane.setHgrow(this, Priority.ALWAYS);

        setOnMouseClicked(event -> {

            mNumber++;

            setText(""+mNumber);
            wyswietlAlert(mNumber);
        });
    }

    public void reset(){
        mNumber = mOriginalNumber;
        setText(""+mNumber);
    }

    private void wyswietlAlert(int no) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Tytuł okna");
        alert.setHeaderText("Przykładowy nagłówek");
        alert.setContentText("" + no);

        alert.showAndWait();
    }
}

public class App extends Application {


    @Override
    public void start(Stage primaryStage) throws Exception {

        Group group = new Group();

        Scene scene = new Scene(group, 500, 500);

        primaryStage.setScene(scene);
        primaryStage.show();

        GridPane gridPane = new GridPane();

        for (int j = 0; j < 10; j++) {
            for (int i = 0; i < 10; i++) {
                gridPane.add(new MyButton(j * 10 + i), i, j);
            }
        }

        VBox vbox = new VBox();
        Button resetButton = new Button("Reset");
        resetButton.setMaxWidth(Double.MAX_VALUE);

        vbox.setVgrow(resetButton, Priority.ALWAYS);
        vbox.setSpacing(10);
        resetButton.setAlignment(Pos.CENTER);

        resetButton.setOnMouseClicked(event -> {
            ObservableList<Node> list =  gridPane.getChildren();

            for(Node node : list)
                ((MyButton) node).reset();

        });

        vbox.getChildren().addAll(gridPane,resetButton);

        group.getChildren().addAll(vbox);

    }
}
