/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junit;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public double dodajLiczby(double a, double b){
        return a+b;
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    }
}
