/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zajecia;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Group group = new Group();
        Scene scene = new Scene(group, 500, 500);

        Image image = new Image(getClass().getResource("grass.png").toString());
        group.getChildren().add(new ImageView(image));

        for (int i = 0; i < 1; i++) {
            AnimationObject object = new AnimationObject(genV.getX(), genV.getY(),10,10, genV.getSize(), genV.getColor());
            object.play();

            group.getChildren().add(object);
        }

        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
