/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junit;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class AppTest {

    @Tag("Kwadrat")
    @Tag("Figury")
    @Test
    public void kwadrat(){

        FiguraGeometryczna figura = new Kwadrat(10);

        assertEquals(100,figura.obliczPole());
        assertEquals(40,figura.obliczObwod());
    }

    @Tag("Trojkat")
    @Tag("Figury")
    @Test
    public void trojkat_1(){
        TrojkatRownoboczny trojkat = new TrojkatRownoboczny(10);

        double wynik1 = 43.30127018922193233800;
        double wynik2 = trojkat.obliczPole((a)->Math.sqrt(3)/4*a*a,10);

        Assertions.assertThat(wynik1-wynik2).isCloseTo(0,Assertions.offset(0.00001));
    }


}
