/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafx.ctrl;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {

        Group group = new Group();

        Scene scene = new Scene(group,500,500);

        primaryStage.setScene(scene);
        primaryStage.show();

        Button button = new Button();
        button.setText("Klawisz");

        Button button1 = new Button();
        button1.setText("111111");

        button.setOnMouseClicked(event -> {
            wyswietlAlert();
        });

        HBox hbox = new HBox();
        hbox.getChildren().addAll(button,button1);

        group.getChildren().addAll(hbox);



    }

    private void wyswietlAlert(){
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Tytuł okna");
        alert.setHeaderText("Przykładowy nagłówek");
        alert.setContentText("Przykładowy tekst");

        alert.showAndWait();
    }
}
