/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafx.ctrl;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

class MyButton extends Button{
    private int mNumber;

    MyButton(int number){

        mNumber = number;

        GridPane.setHgrow(this,Priority.ALWAYS);
        GridPane.setVgrow(this,Priority.ALWAYS);

        this.setMaxHeight(Double.MAX_VALUE);
        this.setMaxWidth(Double.MAX_VALUE);

        this.setText(""+number);

        setOnMouseClicked(event -> {
            wyswietlAlert(number);
        });
    }

    private void wyswietlAlert(int number) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Tytuł okna");
        alert.setHeaderText("Przykładowy nagłówek");
        alert.setContentText("Kliknięto: " + number);

        alert.showAndWait();
    }
}

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {

        Group group = new Group();

        Scene scene = new Scene(group, 500, 500);

        primaryStage.setScene(scene);
        primaryStage.show();

        GridPane grid = new GridPane();
        grid.setBackground(new Background(new BackgroundFill(Color.AZURE,null,null)));

        grid.setAlignment(Pos.CENTER);

        grid.setVgap(10);
        grid.setHgap(10);

        grid.setMaxSize(400,400);


        final int dimension = 5;

        for (int j = 0; j < dimension; j++)
            for (int i = 0; i < dimension; i++) {

                grid.add(new MyButton(j*dimension+i+1), i, j);
            }


        group.getChildren().addAll(grid);

    }

}
