/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InterfaceExample;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;

class Square extends Rectangle{

    Square(double dimension, boolean checked){
        setWidth(dimension);
        setHeight(dimension);

        if(checked)
            setFill(Color.CADETBLUE);
        else
            setFill(Color.BEIGE);

        setOnMouseClicked(new EventHandler<MouseEvent>() {
            @Override
            public void handle(MouseEvent event) {

            }
        });
    }
}

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Group group = new Group();

        Square square = new Square(100,true);

        group.getChildren().add(square);

        Scene scene = new Scene(group,640,640);

        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
