/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InterfaceExample;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;

class Square extends Rectangle{
    int i = 0,j = 0;

    boolean mChecked = false;


    Square(double dimension, boolean checked){

        setWidth(dimension);
        setHeight(dimension);

        setStrokeWidth(0.5);
        setStroke(Color.BLACK);

        mChecked = checked;

        if(mChecked)
            setFill(Color.CADETBLUE);
        else
            setFill(Color.BEIGE);

        setOnMouseClicked(event->{
                System.out.println("["+i+", "+j+"]");

                switchChecked();

        });
    }

    public void setCoordinates(int i, int j){
        this.i = i;
        this.j = j;
    }

    public void switchChecked(){
        mChecked=!mChecked;

        if(mChecked)
            setFill(Color.CADETBLUE);
        else
            setFill(Color.BEIGE);
    }
}

public class App extends Application {
    int[] mData = new int[]{1,0,1,0,0,0,0,1};
    Square[] mGameboard = new Square[8];

    @Override
    public void start(Stage primaryStage) throws Exception {

        Group group = new Group();

        createGameboard();

        for(Square square : mGameboard)
            group.getChildren().add(square);


        Scene scene = new Scene(group,800,800);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public void createGameboard(){

        for(int i=0;i<mData.length;i++){

            Square square;

            if(mData[i]==1)
                square = new Square(100,true);
            else
                square = new Square(100,false);

            square.setTranslateX(100*i);
            square.setCoordinates(i,0);

            mGameboard[i] = square;

        }
    }

}