/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InterfaceExample;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;

class Field extends Rectangle{

    Field(double dimension, boolean checked){
        setWidth(dimension);
        setHeight(dimension);

        if(checked)
            setFill(Color.CADETBLUE);
        else
            setFill(Color.BEIGE);
    }
}

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Group group = new Group();

        Field field = new Field(100,true);

        group.getChildren().add(field);

        Scene scene = new Scene(group,640,640);

        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
