/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.threads;

class ThreadExample extends Thread{
    String name;

    ThreadExample(String name){
        this.name = name;
    }

    @Override
    public void run() {
        while(true) {
            System.out.println("thread: "+name);

            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}

public class App {

    public static void main(String[] args) {

        ThreadExample t0 = new ThreadExample("t0");
        ThreadExample t1 = new ThreadExample("t1");

        t0.start();
        t1.start();

    }
}
