/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.threads;

import java.util.ArrayList;

class ThreadExample extends Thread{
    String name;
    double mData[];
    int no;

    ThreadExample(String name, int threadNo, double[] data){
        this.name = name;
        this.no = threadNo;
        this.mData = data;

    }

    @Override
    public void run() {
        while(true) {
            System.out.println("thread: "+name);

            try {
                Thread.sleep(500);
                mData[no]++;
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}

class ThreadExample0 extends Thread{
    @Override
    public void run(){
        while(true){
            try{
                Thread.sleep(200);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println("napis");
        }
    }
}

public class App {

    static double mDane[] = new double[10];

    static void wyswietlDane(){
        System.out.print("[");

        for(int i=0;i<mDane.length;i++) {
            System.out.print(mDane[i]);
            if(i<mDane.length-1)
                System.out.print(", ");
        }


        System.out.println("]");
    }

    public static void main(String[] args) {

        for(int i=0;i<10;i++)
            mDane[i] = 0;

        wyswietlDane();



        ThreadExample t0 = new ThreadExample("t0",0,mDane);
        ThreadExample t1 = new ThreadExample("t1",1,mDane);

        ThreadExample0 t2 = new ThreadExample0();

        for(int i=0;i<100;i++){
            ThreadExample t = new ThreadExample("t"+i,i,mDane);
            t.setDaemon(true);
            t.start();
        }

        t0.start();
        t1.start();


        Thread wyswietlanie = new Thread(()->{

            while(true) {

                wyswietlDane();
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });

        wyswietlanie.start();
        
    }
}
