/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafx;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setScene(new Scene(new Group()));
        primaryStage.show();
    }
}
