/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lambda;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;

@FunctionalInterface
interface funkcjaMatematyczna{
    double funkcjaDodatkowa(double a, double b);
}


public class App extends Application {
    boolean rectState = false;

    @Override
    public void start(Stage primaryStage) throws Exception {

        Group group = new Group();

        Scene scene = new Scene(group, 500, 500);

        Rectangle rect = new Rectangle();
        rect.setHeight(100);
        rect.setWidth(100);
        rect.setFill(Color.BEIGE);


        group.getChildren().add(rect);


        rect.setOnMouseClicked(event->{
            drawRect(rect);
        });

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    void drawRect(Rectangle rect) {
        if (!rectState)
            rect.setFill(Color.GREEN);
        else
            rect.setFill(Color.BEIGE);

        rectState = !rectState;

        funkcjaMatematyczna dodaj = (double x, double y)-> x+y;

        funkcjaMatematyczna pomnoz = (double a, double b)->a*b;

        wyswietlWynik(10,10,dodaj);
        wyswietlWynik(20,20,pomnoz);

        wyswietlWynik(10,4,(a,b)->a-b);
        wyswietlWynik(40,4,(a,b)->a/b);

    }

    void wyswietlWynik(double a, double b,funkcjaMatematyczna f){
        System.out.println("Wynik działania: "+f.funkcjaDodatkowa(a,b));
    }
}
