/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.junit;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class AppTest {
    @Tag("przyklad")
    @Test
    public void przykladowyTest(){
        System.out.println("Przykladowy test");
    }

    @Tag("math")
    @Test
    public void pierwszyTest(){
        App app = new App();

        System.out.println("porównuje liczby 25 i wynik funkcji");
        assertEquals(20,app.dodaj(10,10));
    }

    @Tag("FiguryGeometryczne")
    @Tag("Kwadrat")
    @Test
    public void kwadrat(){
        FiguraGeometryczna figura = new Kwadrat(10);

        assertEquals(100,figura.obliczPole());
        assertEquals(40,figura.obliczObwod());
    }

    @Tag("FiguryGeometryczne")
    @Tag("Trojkat")
    @Test
    public void trojkat(){
        FiguraGeometryczna figura = new trojkatRownoboczny(10);

        double poleObczone = figura.obliczPole();
        double poleOczekiwane = 43.30127018922193233800;

        double roznica = Math.abs(poleObczone-poleOczekiwane);

        System.out.println("Roznica: "+roznica);
        assertTrue(roznica<7.105427357601002E-10);


        assertEquals(30,figura.obliczObwod());
    }


}
