/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thread;

public class App {
    static double mDane[] = new double[10];

    static void dodajDane(){
        for(int i=0;i<mDane.length;i++)
            mDane[i] = i;
    }

    static void wyswietlDane(){
        System.out.print("[");

        for(int i=0;i<mDane.length;i++){
            System.out.print(mDane[i]);

            if(i<mDane.length-1)
                System.out.print(", ");
        }

        System.out.print("]");
    }

    public static void main(String[] args) {
        dodajDane();
        wyswietlDane();

        while(true){
            System.out.println("1");
            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

    }
}
