/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.threads.exceptions;

import java.io.IOException;

public class App {

    public static void main(String[] args){
        try {
            System.out.println("kod...");
            metchod1();
            System.out.println("Dalszy kod...");
        }catch(IOException e){
            e.printStackTrace();
            System.out.println("Przechwycono wyjątek");
        }
    }

    public static void metchod1() throws IOException {
        metchod0();
    }

    public static void metchod0() throws IOException {
        exceptionMetchod();
    }

    public static void exceptionMetchod() throws IOException {
        throw new IOException("Coś poszło nie tak...");
    }
}
